-- Hammer
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 1, 'hammer 1', 'big hammer 1', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 2, 'hammer 2', 'big hammer 2', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 3, 'hammer 3', 'big hammer 3', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 4, 'hammer 4', 'big hammer 4', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 5, 'hammer 5', 'big hammer 5', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 6, 'hammer 6', 'big hammer 6', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 7, 'hammer 7', 'big hammer 7', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 8, 'hammer 8', 'big hammer 8', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES ( 9, 'hammer 9', 'big hammer 9', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (10, 'hammer10', 'big hammer10', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (11, 'hammer11', 'big hammer11', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (12, 'hammer12', 'big hammer12', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (13, 'hammer13', 'big hammer13', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (14, 'hammer14', 'big hammer14', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (15, 'hammer15', 'big hammer15', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (16, 'hammer16', 'big hammer16', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (17, 'hammer17', 'big hammer17', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (18, 'hammer18', 'big hammer18', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (19, 'hammer19', 'big hammer19', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (20, 'hammer20', 'big hammer20', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (21, 'hammer21', 'big hammer21', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (22, 'hammer22', 'big hammer22', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (23, 'hammer23', 'big hammer23', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (24, 'hammer24', 'big hammer24', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (25, 'hammer25', 'big hammer25', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (26, 'hammer26', 'big hammer26', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (27, 'hammer27', 'big hammer27', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (28, 'hammer28', 'big hammer28', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (29, 'hammer29', 'big hammer29', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (30, 'hammer30', 'big hammer30', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (31, 'hammer31', 'big hammer31', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (32, 'hammer32', 'big hammer32', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (33, 'hammer33', 'big hammer33', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (34, 'hammer34', 'big hammer34', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (35, 'hammer35', 'big hammer35', 'acme hammer')
INSERT INTO PRODUCTS( id, name, description ,manufacturer) VALUES (36, 'hammer36', 'big hammer36', 'acme hammer')